apiVersion: v1
kind: Service
metadata:
  name: airsonic
  labels:
    app: airsonic
spec:
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
  selector:
    app: airsonic
  type: ClusterIP
