apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsonic
  labels:
    app: airsonic
spec:
  replicas: 0
  selector:
    matchLabels:
      app: airsonic
  template:
    metadata:
      labels:
        app: airsonic
    spec:
      volumes:
        - name: airsonic-music
          persistentVolumeClaim:
            claimName: airsonic-music-pvc
        - name: airsonic-config
          persistentVolumeClaim:
            claimName: airsonic-config-pvc
        - name: airsonic-podcasts
          persistentVolumeClaim:
            claimName: airsonic-podcasts-pvc
        - name: airsonic-playlists
          persistentVolumeClaim:
            claimName: airsonic-playlists-pvc
      containers:
        - name: airsonic
          image: {{ .Values.images.airsonic.image }}:{{ .Values.images.airsonic.tag }}
          ports:
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: airsonic-music
              mountPath: /music
            - name: airsonic-config
              mountPath: /config
            - name: airsonic-podcasts
              mountPath: /podcasts
            - name: airsonic-playlists
              mountPath: /playlists
          imagePullPolicy: {{ .Values.images.airsonic.imagePullPolicy }}
