apiVersion: v1
kind: Service
metadata:
  name: calibre
  labels:
    app: calibre
spec:
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: calibre
  type: ClusterIP
