apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  labels:
    app: changedetection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetection
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      volumes:
        - name: changedetection-data
          persistentVolumeClaim:
            claimName: changedetection-data-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: changedetection
          image: {{ .Values.images.changedetection.image }}:{{ .Values.images.changedetection.tag }}
          env:
            - name: PLAYWRIGHT_DRIVER_URL
              value: ws://localhost:3000/?stealth=1&--disable-web-security=true
            # - name: WEBDRIVER_URL
            #   value: "http://localhost:4444/wd/hub"
            - name: BASE_URL
              value: "https://changes.sethpyle.com"
            - name: FETCH_WORKERS
              value: "1"
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: changedetection-data
              mountPath: /datastore
          imagePullPolicy: {{ .Values.images.changedetection.imagePullPolicy }}
        - name: browserless
          image: browserless/chrome:latest
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
        # - name: seleniarm
        #   image: seleniarm/standalone-chromium:111.0
        #   env:
        #     - name: VNC_NO_PASSWORD
        #       value: "1"
        #     - name: SCREEN_WIDTH
        #       value: "1920"
        #     - name: SCREEN_HEIGHT
        #       value: "1080"
        #     - name: SCREEN_DEPTH
        #       value: "24"
        #   volumeMounts:
        #     - mountPath: /dev/shm
        #       name: dshm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: changedetection
  labels:
    app: changedetection
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: changedetection
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: changedetection-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - changes.sethpyle.com
  rules:
    - host: changes.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: changedetection
                port:
                  number: 5000
 
