apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.images.cloudflared.image }}:{{ .Values.images.cloudflared.tag }}"
          args: ["tunnel", "run", "--token", {{ .Values.cloudflared.token }}]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          imagePullPolicy: {{ .Values.images.discordIrc.imagePullPolicy }}

