apiVersion: v1
kind: Service
metadata:
  name: delegation-nginx
  labels:
    app: delegation-nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: delegation-nginx
  type: ClusterIP
