---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart
  namespace: homelab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: homelab 
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["teddit", "youtube"]
    verbs: ["get", "patch", "list", "watch"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart
  namespace: homelab 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart
subjects:
  - kind: ServiceAccount
    name: deployment-restart
    namespace: homelab
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-teddit
  namespace: homelab 
spec:
  concurrencyPolicy: Forbid
  schedule: '* 0 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deployment-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: rancher/kubectl:v1.23.7 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/teddit'
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-invidious
  namespace: homelab 
spec:
  concurrencyPolicy: Forbid
  schedule: '* */3 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deployment-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: rancher/kubectl:v1.23.7 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/youtube'
