apiVersion: v1
kind: Service
metadata:
  name: matrixdiscord
  labels:
    app: matrixdiscord
spec:
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
  selector:
    app: matrixdiscord
  type: ClusterIP