apiVersion: v1
kind: Service
metadata:
  name: dsm
  labels:
    app: dsm
spec:
  type: ExternalName
  externalName: storage.sethpyle.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsm-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - dsm.sethpyle.com
  rules:
    - host: dsm.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: dsm
                port:
                  number: 5000