apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  labels:
    app: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-pvc
      containers:
        - name: postgres
          image: "{{ .Values.images.freshrss.image}}:{{ .Values.images.freshrss.tag }}"
          env:
            - name: "TZ"
              value: "America/Chicago"
          ports:
            - containerPort: {{ .Values.freshrss.port }}
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: freshrss-data
              mountPath: /config
          imagePullPolicy: {{ .Values.images.freshrss.imagePullPolicy }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  labels:
    app: freshrss
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.freshrss.port }}
      targetPort: {{ .Values.freshrss.port }}
  selector:
    app: freshrss
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshrss-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - freshrss.sethpyle.com
  rules:
    - host: freshrss.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: freshrss
                port:
                  number: {{ .Values.freshrss.port }}
