---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 500Mi