apiVersion: v1
kind: Service
metadata:
  name: freshrss
  labels:
    app: freshrss
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.freshrss.port }}
      targetPort: {{ .Values.freshrss.port }}
  selector:
    app: freshrss
  type: ClusterIP
