apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-config
          persistentVolumeClaim:
            claimName: grafana-config-pvc
      containers:
        - name: grafana
          image: {{ .Values.images.grafana.image }}:{{ .Values.images.grafana.tag }}
          env:
            - name: "GF_SERVER_ROOT_URL"
              value: "https://grafana.sethpyle.com"
            - name: "GF_AUTH_GENERIC_OAUTH_SCOPES"
              value: "openid profile email"
            - name: "GF_AUTH_GENERIC_OAUTH_CLIENT_ID"
              value: "kVnxdJtUo1YiUhVBW6PPgJlgtd2lVxTYNoC66Hvj"
            - name: "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET"
              value: "y2NKCxi7jBvza8B8XTHy7B23r7dbafd655topJsrUaFt5goAJvKIDG2poTmmD5Cqc8flay3vFcgHCFj1CqyAZpy2uJb2sjOSLy5t50UFfHGa59AowpTjlqOjGoNkKtbG"
            - name: "GF_AUTH_GENERIC_OAUTH_AUTH_URL"
              value: "https://auth.sethpyle.com/application/o/authorize/"
            - name: "GF_AUTH_GENERIC_OAUTH_TOKEN_URL"
              value: "https://auth.sethpyle.com/application/o/token/"
            - name: "GF_AUTH_GENERIC_OAUTH_API_URL"
              value: "https://auth.sethpyle.com/application/o/userinfo/"
            - name: "GF_AUTH_GENERIC_OAUTH_ENABLED"
              value: "true"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "500Mi"
              cpu: "1"
          volumeMounts:
            - name: grafana
              mountPath: /var/lib/grafana
          imagePullPolicy: {{ .Values.images.grafana.imagePullPolicy }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    traefik.frontend.passHostHeader: "false"
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - grafana.sethpyle.com
  rules:
    - host: grafana.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000
