apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
      containers:
        - name: homeassistant
          image: "{{ .Values.images.homeassistant.image }}:{{ .Values.images.homeassistant.tag }}"
          ports:
            - containerPort: 8123
              protocol: TCP
          env:
            - name: TZ
              value: 'America/Chicago'
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: homeassistant
              mountPath: /config
          imagePullPolicy: {{ .Values.images.homeassistant.imagePullPolicy }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
  selector:
    app: homeassistant
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress
  annotations:
    traefik.frontend.passHostHeader: "false"
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - home.sethpyle.com
  rules:
    - host: home.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: homeassistant
                port:
                  number: 8123
