apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube
  labels:
    app: youtube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      volumes:
        - name: invidious-config
          secret:
            secretName: invidious-config
      containers:
        - name: youtube
          image: {{ .Values.images.youtube.image }}:{{ .Values.images.youtube.tag }}
          ports:
            - containerPort: {{ .Values.youtube.port }}
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: invidious-config
              mountPath: /invidious/config/config.yml
              subPath: invidious-config.yml
          imagePullPolicy: {{ .Values.images.youtube.imagePullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: youtube
  labels:
    app: youtube
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.youtube.port }}
      targetPort: {{ .Values.youtube.port }}
  selector:
    app: youtube
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - youtube.sethpyle.com
  rules:
    - host: youtube.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: youtube
                port:
                  number: {{ .Values.youtube.port }}