apiVersion: v1
kind: Service
metadata:
  name: irc
  labels:
    app: irc
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.irc.port }}
      targetPort: {{ .Values.irc.port }}
  selector:
    app: irc
  type: ClusterIP
