apiVersion: apps/v1
kind: Deployment
metadata:
  name: irc
  labels:
    app: irc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irc
  template:
    metadata:
      labels:
        app: irc
    spec:
      volumes:
        - name: irc-data
          persistentVolumeClaim:
            claimName: irc-pvc
      containers:
        - name: irc
          image: {{ .Values.images.irc.image }}:{{ .Values.images.irc.tag }}
          ports:
            - containerPort: {{ .Values.irc.port }}
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: irc-data
              mountPath: /var/opt/thelounge
          imagePullPolicy: {{ .Values.images.irc.imagePullPolicy }}

