apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: irc-ingress
spec:
  tls:
    - hosts:
        - irc.sethpyle.com
  rules:
    - host: irc.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: irc
                port:
                  number: {{ .Values.irc.port }}
