apiVersion: v1
kind: Service
metadata:
  name: matrix
  labels:
    app: matrix
spec:
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
  selector:
    app: matrix
  type: ClusterIP
