apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
      containers:
        - name: postgres
          image: {{ .Values.images.n8n.image}}:{{ .Values.images.n8n.tag }}
          ports:
            - containerPort: {{ .Values.n8n.port }}
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: postgres
            - name: DB_POSTGRESDB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_POSTGRESDB_DATABASE
              value: {{ .Values.postgres.db }}
            - name: DB_POSTGRESDB_PASSWORD
              value: {{ .Values.postgres.pass }}
            - name: DB_POSTGRESDB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: DB_POSTGRESDB_SCHEMA
              value: "n8n"
            - name: N8N_PORT
              value: "{{ .Values.n8n.port }}"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "{{ .Values.n8n.useBasicAuth }}"
            - name: N8N_BASIC_AUTH_USER
              value: {{ .Values.n8n.user }}
            - name: N8N_BASIC_AUTH_PASSWORD
              value: {{ .Values.n8n.pass }}
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          imagePullPolicy: {{ .Values.images.n8n.imagePullPolicy }}