apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - n8n.sethpyle.com
  rules:
    - host: n8n.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: n8n
                port:
                  number: {{ .Values.n8n.port }}
