apiVersion: apps/v1
kind: Deployment
metadata:
  name: nitter
  labels:
    app: nitter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nitter
  template:
    metadata:
      labels:
        app: nitter
    spec:
      containers:
        - name: nitter
          image: {{ .Values.images.nitter.image }}:{{ .Values.images.nitter.tag }}
          env:
            - name: NITTER_HOST
              value: 'nitter.sethpyle.com'
            - name: REDIS_HOST
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
            - name: REPLACE_TWITTER
              value: 'nitter.sethpyle.com'
            - name: REPLACE_YOUTUBE
              value: 'youtube.sethpyle.com'
            - name: TITLE
              value: 'Seths Private Twitter'
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.nitter.port }}
              protocol: TCP
          imagePullPolicy: {{ .Values.images.nitter.imagePullPolicy }}
