apiVersion: v1
kind: Service
metadata:
  name: nitter
  labels:
    app: nitter
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.nitter.port }}
      targetPort: {{ .Values.nitter.port }}
  selector:
    app: nitter
  type: ClusterIP