apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nitter-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - nitter.sethpyle.com
  rules:
    - host: nitter.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nitter
                port:
                  number: {{ .Values.nitter.port }}
