apiVersion: v1
kind: Service
metadata:
  name: nocodb
  labels:
    app: nocodb
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nocodb
  type: ClusterIP
