apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
  labels:
    app: nocodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nocodb
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      volumes:
        - name: nocodb-data
          persistentVolumeClaim:
            claimName: nocodb-data-pvc
      containers:
        - name: nocodb
          image: "{{ .Values.images.nocodb.image }}:{{ .Values.images.nocodb.tag }}"
          env:
            - name: "NC_DB"
              value: "pg://postgres:5432?u=nocodb&p=nocodb&d=nocodb"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: nocodb-data
              mountPath: /usr/app/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nocodb
  labels:
    app: nocodb
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nocodb
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nocodb-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - db.sethpyle.com
  rules:
    - host: db.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nocodb
                port:
                  number: 8080
