apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
  labels:
    app: nocodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nocodb
  template:
    metadata:
      labels:
        app: nocodb
    spec:
      containers:
        - name: nocodb
          image: {{ .Values.images.nocodb.image }}:{{ .Values.images.nocodb.tag }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
          - secretRef:
              name: nocodb-secret
          imagePullPolicy: {{ .Values.images.nocodb.imagePullPolicy }}