apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      volumes:
        - name: nodered-data
          persistentVolumeClaim:
            claimName: nodered-pvc
        - name: nodered-settings
          configMap:
            name: nodered-settings-configmap
      containers:
        - name: nodered
          image: {{ .Values.images.nodered.image }}:{{ .Values.images.nodered.tag }}
          ports:
            - containerPort: {{ .Values.nodered.port }}
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: nodered-data
              mountPath: /data
            - name: nodered-settings
              mountPath: /data/settings.js
              subPath: settings.js
          imagePullPolicy: {{ .Values.images.nodered.imagePullPolicy }}