apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      volumes:
        - name: nodered-data
          persistentVolumeClaim:
            claimName: nodered-pvc
        - name: nodered-settings
          configMap:
            name: nodered-settings-configmap
      containers:
        - name: nodered
          image: "{{ .Values.images.nodered.image }}:{{ .Values.images.nodered.tag }}"
          ports:
            - containerPort: {{ .Values.nodered.port }}
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          volumeMounts:
            - name: nodered-data
              mountPath: /data
            - name: nodered-settings
              mountPath: /data/settings.js
              subPath: settings.js
          imagePullPolicy: {{ .Values.images.nodered.imagePullPolicy }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodered-settings-configmap
data:
  settings.js: |-
{{ .Files.Get "nodered-settings.js" | indent 4}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.nodered.port }}
      targetPort: {{ .Values.nodered.port }}
  selector:
    app: nodered
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nodered-smtp
  labels:
    app: nodered
spec:
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
  selector:
    app: nodered
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - nodered.sethpyle.com
  rules:
    - host: nodered.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nodered
                port:
                  number: {{ .Values.nodered.port }}
