apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.nodered.port }}
      targetPort: {{ .Values.nodered.port }}
  selector:
    app: nodered
  type: ClusterIP