apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      volumes:
        - name: nodered-data
          persistentVolumeClaim:
            claimName: nodered-pvc
        - name: nodered-settings
          configMap:
            name: nodered-settings-configmap
        - name: nodered
          image: {{ .Values.images.nodered.image }}:{{ .Values.images.nodered.tag }}
          ports:
            - containerPort: {{ .Values.nodered.port }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nodered-data
              mountPath: /data
            - name: nodered-settings
              mountPath: /usr/src/node-red/.node-red/settings.js
          imagePullPolicy: {{ .Values.images.nodered.imagePullPolicy }}