apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - nodered.sethpyle.com
  rules:
    - host: nodered.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nodered
                port:
                  number: {{ .Values.nodered.port }}