apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup
spec:
  schedule: "30 23 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: pg-backup
              persistentVolumeClaim:
                claimName: pg-backup-pvc
          containers:
            - name: pg-backup
              image: {{ .Values.images.pgBackup.image }}:{{ .Values.images.pgBackup.tag }}
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: 'aws-storage-creds'
                      key: 'AWS_ACCESS_KEY_ID'
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: 'aws-storage-creds'
                      key: 'AWS_SECRET_ACCESS_KEY'
                - name: S3_BUCKET
                  value: {{ .Values.pgBackup.s3Bucket }}
                - name: PG_USER
                  value: {{ .Values.postgres.user }}
                - name: PG_PASS
                  value: {{ .Values.postgres.pass }}
                - name: PG_HOST
                  value: postgres
                - name: PG_PORT
                  value: "{{ .Values.postgres.port }}"
                - name: DISCORD_WEBHOOK
                  value: {{ .Values.pgBackup.discordWebhook }}
              command:
                - /bin/sh
                - -c
                - cd /home/root; ls; bash do-backup.sh
              imagePullPolicy: {{ .Values.images.pgBackup.imagePullPolicy }}
              resources:
                requests:
                  memory: "150Mi"
                  cpu: "250m"
                limits:
                  memory: "300Mi"
                  cpu: "500m"
              volumeMounts:
                - name: pg-backup
                  mountPath: /backup
          restartPolicy: OnFailure
      backoffLimit: 3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
