apiVersion: apps/v1
kind: Deployment
metadata:
  name: piholeexporter
  labels:
    app: piholeexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piholeexporter
  template:
    metadata:
      labels:
        app: piholeexporter
    spec:
      containers:
        - name: piholeexporter
          image: {{ .Values.images.piholeexporter.image }}:{{ .Values.images.piholeexporter.tag }}
          env:
            - name: 'PIHOLE_API_TOKEN'
              valueFrom:
                secretKeyRef:
                  name: pihole
                  key: api_token
                  optional: false
            - name: 'PIHOLE_HOSTNAME'
              value: '192.168.1.1'
            - name: 'PORT'
              value: '9617'
            - name: 'PIHOLE_PORT'
              value: '8080'
          ports:
            - containerPort: 9617
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          imagePullPolicy: {{ .Values.images.piholeexporter.imagePullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: piholeexporter
  labels:
    app: piholeexporter
spec:
  ports:
    - protocol: TCP
      port: 9617
      targetPort: 9617
  selector:
    app: piholeexporter
  type: ClusterIP
