apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planka-ingress  
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - planka.sethpyle.com
  rules:
    - host: planka.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: planka
                port:
                  number: {{ .Values.planka.port }}
