apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.images.redis.image }}:{{ .Values.images.redis.tag }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          imagePullPolicy: {{ .Values.images.redis.imagePullPolicy }}