apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttrss
  labels:
    app: ttrss
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ttrss
  template:
    metadata:
      labels:
        app: ttrss
    spec:
      volumes:
        - name: rss-data
          persistentVolumeClaim:
            claimName: ttrss-pvc
      containers:
        - name: postgres
          image: {{ .Values.images.rss.image}}:{{ .Values.images.rss.tag }}
          ports:
            - containerPort: {{ .Values.rss.port }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_NAME
              value: {{ .Values.postgres.db }}
            - name: DB_PASS
              value: {{ .Values.postgres.pass }}
            - name: DB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: SELF_URL_PATH
              value: 'https://rss.sethpyle.com'
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: rss-data
              mountPath: /config
          imagePullPolicy: {{ .Values.images.rss.imagePullPolicy }}

