apiVersion: v1
kind: Service
metadata:
  name: ttrss
  labels:
    app: ttrss
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.rss.port }}
      targetPort: {{ .Values.rss.port }}
  selector:
    app: ttrss
  type: ClusterIP
