apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-bridge
  labels:
    app: rss-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-bridge
  template:
    metadata:
      labels:
        app: rss-bridge
    spec:
      volumes:
        - name: rss-bridge-data
          persistentVolumeClaim:
            claimName: rss-bridge-pvc
      containers:
        - name: rss-bridge
          image: {{ .Values.images.rssBridge.image }}:{{ .Values.images.rssBridge.tag }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: rss-bridge-data
              mountPath: /config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-bridge-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rss-bridge
  labels:
    app: rss-bridge
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: rss-bridge
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rss-bridge-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - rssbridge.sethpyle.com
  rules:
    - host: rssbridge.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: rss-bridge
                port:
                  number: 80
