apiVersion: v1
kind: Service
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.searxng.port }}
      targetPort: {{ .Values.searxng.port }}
  selector:
    app: searxng
  type: ClusterIP