apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  replicas: {{ .Values.searxng.replicaCount }}
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      volumes:
        - name: searxng-settings
          configMap:
            name: searxng-config-configmap
      containers:
        - name: searxng
          image: {{ .Values.images.searxng.image }}:{{ .Values.images.searxng.tag }}
          ports:
            - containerPort: {{ .Values.searxng.port }}
              protocol: TCP
          env:
            - name: SEARXNG_SECRET
              value: {{ .Values.searxng.secret }}
            - name: INSTANCE_NAME
              value: "homelab"
            - name: BASE_URL
              value: {{ .Values.searxng.baseURL }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
            - name: searxng-settings
              mountPath: /etc/searxng/uwsgi.ini
              subPath: searxng-uwsgi.ini
            - name: searxng-settings
              mountPath: /etc/searxng/settings.yaml
              subPath: searxng-settings.yaml
          imagePullPolicy: {{ .Values.images.searxng.imagePullPolicy }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config-configmap
data:
{{ (.Files.Glob "config_files/*").AsConfig | indent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - search.sethpyle.com
  rules:
    - host: search.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: searxng
                port:
                  number: {{ .Values.searxng.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.searxng.port }}
      targetPort: {{ .Values.searxng.port }}
  selector:
    app: searxng
  type: ClusterIP