apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - search.sethpyle.com
  rules:
    - host: search.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: searxng
                port:
                  number: {{ .Values.searxng.port }}