apiVersion: apps/v1
kind: Deployment
metadata:
  name: teddit
  labels:
    app: teddit
spec:
  replicas: 0
  selector:
    matchLabels:
      app: teddit
  template:
    metadata:
      labels:
        app: teddit
    spec:
      containers:
        - name: teddit
          image: "{{ .Values.images.teddit.image }}:{{ .Values.images.teddit.tag }}"
          ports:
            - containerPort: {{ .Values.teddit.port }}
              protocol: TCP
          env:
            - name: DOMAIN
              value: 'teddit.sethpyle.com'
            - name: USE_HELMET
              value: 'true'
            - name: USE_HELMET_HSTS
              value: 'true'
            - name: TRUST_PROXY
              value: 'true'
            - name: TRUST_PROXY_ADDRESS
              value: '10.0.0.0/8'
            - name: NSFW_ENABLED
              value: 'false'
            - name: REDIS_HOST
              value: 'redis'
            - name: DOMAIN_REPLACEMENTS
              value: '[["twitter.com", "nitter.sethpyle.com"], ["m.youtube.com", "youtube.sethpyle.com"], ["www.youtube.com", "youtube.sethpyle.com"], ["youtube.com", "youtube.sethpyle.com"], ["youtu.be", "youtube.sethpyle.com"]]'
            # - name: USE_REDDIT_OAUTH
            #   value: 'true'
            # - name: REDDIT_APP_ID
            #   value: {{ .Values.teddit.appID }}
            - name: THEME
              value: 'nord'
            - name: REDIS_ENABLED
              value: 'true'
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"
          imagePullPolicy: {{ .Values.images.teddit.imagePullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: teddit
  labels:
    app: teddit
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.teddit.port }}
      targetPort: {{ .Values.teddit.port }}
  selector:
    app: teddit
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teddit-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - teddit.sethpyle.com
  rules:
    - host: teddit.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: teddit
                port:
                  number: {{ .Values.teddit.port }}
