apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teddit-ingress
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - teddit.sethpyle.com
  rules:
    - host: teddit.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: teddit
                port:
                  number: {{ .Values.teddit.port }}
