apiVersion: v1
kind: Service
metadata:
  name: teddit
  labels:
    app: teddit
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.teddit.port }}
      targetPort: {{ .Values.teddit.port }}
  selector:
    app: teddit
  type: ClusterIP
