apiVersion: apps/v1
kind: Deployment
metadata:
  name: nitter
  labels:
    app: nitter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nitter
  template:
    metadata:
      labels:
        app: nitter
    spec:
      containers:
        - name: nitter
          image: {{ .Values.images.nitter.image }}:{{ .Values.images.nitter.tag }}
          env:
            - name: NITTER_HOST
              value: 'nitter.sethpyle.com'
            - name: REDIS_HOST
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
            - name: REPLACE_TWITTER
              value: 'nitter.sethpyle.com'
            - name: REPLACE_YOUTUBE
              value: 'youtube.sethpyle.com'
            - name: TITLE
              value: 'Seths Private Twitter'
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.nitter.port }}
              protocol: TCP
          imagePullPolicy: {{ .Values.images.nitter.imagePullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: nitter
  labels:
    app: nitter
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.nitter.port }}
      targetPort: {{ .Values.nitter.port }}
  selector:
    app: nitter
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nitter-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - secretName: "le-cert"
    - hosts:
        - nitter.sethpyle.com
  rules:
    - host: nitter.sethpyle.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nitter
                port:
                  number: {{ .Values.nitter.port }}
