# Default values for homelab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent

images:
  ghost:
    image: ghost
    tag: 4.21.0
    imagePullPolicy: IfNotPresent
  postgres:
    image: postgres
    tag: 9.6.23
    imagePullPolicy: IfNotPresent
  rss:
    image: wangqiru/ttrss
    tag: latest
    imagePullPolicy: IfNotPresent
  irc:
    image: thelounge/thelounge
    tag: 4.2.0
    imagePullPolicy: IfNotPresent
  pgBackup:
    image: sethpyle/pg-backup
    tag: 1.0.1
    imagePullPolicy: IfNotPresent
  calibre:
    image: linuxserver/calibre-web
    tag: 2021.11.04
    imagePullPolicy: IfNotPresent
  airsonic:
    image: linuxserver/airsonic
    tag: 10.6.2
    imagePullPolicy: IfNotPresent
  n8n:
    image: n8nio/n8n
    tag: 0.148.0
    imagePullPolicy: IfNotPresent
  nodered:
    image: nodered/node-red
    tag: 2.1.3
    imagePullPolicy: IfNotPresent

postgres:
  user:
  pass:
  db:
  port: 5432

rss:
  port: 80

n8n:
  port: 5678
  useBasicAuth: true
  user:
  pass:

irc:
  port: 9000

nodered:
  port: 1880

pgBackup:
  s3Bucket:
  discordWebhook:

aws:
  key:
  secret:
  defaultRegion: us-east-1
