# Default values for homelab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent

images:
  ghost:
    image: ghost
    tag: 4.21.0
    imagePullPolicy: IfNotPresent
  postgres:
    image: postgres
    tag: 9.6.23
    imagePullPolicy: IfNotPresent
  rss:
    image: wangqiru/ttrss
    tag: latest
    imagePullPolicy: IfNotPresent
  irc:
    image: thelounge/thelounge
    tag: 4.2.0
    imagePullPolicy: IfNotPresent
  pgBackup:
    image: sethpyle/pg-backup
    tag: 1.0.1
    imagePullPolicy: IfNotPresent
  calibre:
    image: linuxserver/calibre-web
    tag: 2021.11.04
    imagePullPolicy: IfNotPresent

postgres:
  user:
  pass:
  db:
  port: 5432

rss:
  port: 80

irc:
  port: 9000

pgBackup:
  s3Bucket:
  discordWebhook:

aws:
  key:
  secret:
  defaultRegion: us-east-1
