# Default values for homelab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent

images:
  ghost:
    image: ghost
    tag: 4.21.0
    imagePullPolicy: IfNotPresent
  postgres:
    image: postgres
    tag: 15.3
    imagePullPolicy: IfNotPresent
  rss:
    image: wangqiru/ttrss
    tag: latest
    imagePullPolicy: IfNotPresent
  irc:
    image: thelounge/thelounge
    tag: 4.2.0
    imagePullPolicy: IfNotPresent
  pgBackup:
    image: sethpyle/pg-backup
    tag: 2.1.0
    imagePullPolicy: Always
  calibre:
    image: linuxserver/calibre-web
    tag: 0.6.20
    imagePullPolicy: IfNotPresent
  airsonic:
    image: linuxserver/airsonic-advanced
    tag: 11.0.0
    imagePullPolicy: IfNotPresent
  n8n:
    image: n8nio/n8n
    tag: 0.181.2
    imagePullPolicy: IfNotPresent
  nodered:
    image: nodered/node-red
    tag: 3.0.0
    imagePullPolicy: IfNotPresent
  matrix:
    image: matrixdotorg/synapse
    tag: v1.47.0
    imagePullPolicy: IfNotPresent
  delegation:
    image: nginx
    tag: 1.21.4
    imagePullPolicy: IfNotPresent
  searxng:
    image: searxng/searxng
    tag: 2023.10.1-d56b31d67
    imagePullPolicy: IfNotPresent
  grafana:
    image: grafana/grafana
    tag: 8.3.2-ubuntu
    imagePullPolicy: IfNotPresent
  matrixdiscord:
    image: sethpyle/matrix-appservice-discord
    tag: 1.0.0
    imagePullPolicy: IfNotPresent
  homeassistant:
    image: homeassistant/home-assistant
    tag: 2023.9
    imagePullPolicy: IfNotPresent
  planka:
    image: meltyshev/planka
    tag: 1.0.0-beta
    imagePullPolicy: IfNotPresent
  teddit:
    image: teddit/teddit
    tag: latest
    imagePullPolicy: Always
  redis:
    image: redis
    tag: 6.2.6
    imagePullPolicy: IfNotPresent
  nitter:
    image: zedeus/nitter
    tag: d7ca353a55ea3440a2ec1f09155951210a374cc7-arm64
    imagePullPolicy: IfNotPresent
  youtube:
    image: quay.io/invidious/invidious
    tag: 34508966027fce3f460d9670eeecef67b92565a0-arm64
    imagePullPolicy: IfNotPresent
  nocodb:
    image: nocodb/nocodb
    tag: 0.84.16
    imagePullPolicy: IfNotPresent
  freshrss:
    image: lscr.io/linuxserver/freshrss
    tag: 1.21.0
    imagePullPolicy: IfNotPresent
  piholeexporter:
    image: ekofr/pihole-exporter
    tag: v0.3.0
    imagePullPolicy: IfNotPresent
  flame:
    image: pawelmalak/flame
    tag: multiarch2.3.0
    imagePullPolicy: IfNotPresent
  dashy:
    image: lissy93/dashy
    tag: 2.1.1
    imagePullPolicy: IfNotPresent
  wikijs:
    image: ghcr.io/requarks/wiki
    tag: 2.5.291
    imagePullPolicy: IfNotPresent
  gitea:
    image: gitea/gitea
    tag: 1.20.4-linux-arm64
    imagePullPolicy: IfNotPresent
  firefly:
    image: fireflyiii/core
    tag: version-5.7.9
    imagePullPolicy: IfNotPresent
  fidi:
    image: fireflyiii/data-importer
    tag: latest
    imagePullPolicy: IfNotPresent
  ngircd:
    image: linuxserver/ngircd
    tag: version-26.1-r0
    imagePullPolicy: IfNotPresent
  discordIrc:
    image: sethpyle/discord-irc
    tag: latest
    imagePullPolicy: IfNotPresent
  linkding:
    image: sissbruecker/linkding
    tag: 1.17.2
    imagePullPolicy: IfNotPresent
  vikunjaApi:
    image: vikunja/api
    tag: 0.21.0
    imagePullPolicy: IfNotPresent
  vikunjaFrontend:
    image: vikunja/frontend
    tag: 0.21.0
    imagePullPolicy: IfNotPresent
  rsApi:
    image: ghcr.io/sethpyle376/rs_api_server
    tag: v0.6.0
    imagePullPolicy: IfNotPresent
  cloudflared:
    image: cloudflare/cloudflared
    tag: 2022.12.1
    imagePullPolicy: IfNotPresent
  changedetection:
    image: dgtlmoon/changedetection.io
    tag: 0.45.3
    imagePullPolicy: IfNotPresent
  rssBridge:
    image: rssbridge/rss-bridge
    tag: sha-8486c0f
    imagePullPolicy: IfNotPresent
  trilium:
    image: zadam/trilium
    tag: 0.60.4
    imagePullPolicy: IfNotPresent
  joplin:
    image: florider89/joplin-server
    tag: 2.10.11
    imagePullPolicy: IfNotPresent
  lemmy:
    image: dessalines/lemmy
    tag: 0.17.3-linux-arm64
    imagePullPolicy: IfNotPresent
  lemmyUi:
    image: dessalines/lemmy-ui
    tag: 0.17.3-linux-arm64
    imagePullPolicy: IfNotPresent
  pictrs:
    image: asonix/pictrs
    tag: 0.3.3
    imagePullPolicy: IfNotPresent
  blog:
    image: ghcr.io/sethpyle376/blog
    tag: v1.1.0
    imagePullPolicy: IfNotPresent
  authentik:
    image: ghcr.io/goauthentik/server
    tag: 2023.8.3
    imagePullPolicy: IfNotPresent
  radicale:
    image: tomsquest/docker-radicale
    tag: 3.1.8.3
    imagePullPolicy: IfNotPresent
  homepage:
    image: ghcr.io/benphelps/homepage
    tag: v0.7.0
    imagePullPolicy: IfNotPresent
  ntfy:
    image: binwiederhier/ntfy
    tag: v2.7.0
    imagePullPolicy: IfNotPresent
  nocodb:
    image: nocodb/nocodb
    tag: 0.202.4
    imagePullPolicy: IfNotPresent

postgres:
  user:
  pass:
  db:
  port: 5432

rss:
  port: 80

n8n:
  port: 5678
  useBasicAuth: true
  user:
  pass:

irc:
  port: 9000

nodered:
  port: 1880

pgBackup:
  s3Bucket:
  discordWebhook:

aws:
  key:
  secret:
  defaultRegion: us-east-1

searxng:
  port: 8080
  secret:
  baseURL:
  replicaCount: 1

planka:
  port: 1337
  connectionString:
  secretKey:

teddit:
  port: 8080
  appID:

redis:
  port: 6379

nitter:
  port: 8080

youtube:
  port: 3000

freshrss:
  port: 80

firefly:
  key:
  user:
  pass:
  accessToken:

vikunja:
  mailerUsername:
  mailerPassword:

githubRunner:
  accessToken:

cloudflared:
  token:

cloudflaredLemmy:
  token:

authentik:
  secretKey:

radicale:
  port: 5232

ntfy:
  port: 80
