# Default values for homelab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullPolicy: IfNotPresent

images:
  ghost:
    image: ghost
    tag: 4.21.0
    imagePullPolicy: IfNotPresent
  postgres:
    image: postgres
    tag: 9.6.23
    imagePullPolicy: IfNotPresent
  rss:
    image: wangqiru/ttrss
    tag: latest
    imagePullPolicy: IfNotPresent
  irc:
    image: thelounge/thelounge
    tag: 4.2.0
    imagePullPolicy: IfNotPresent
  pgBackup:
    image: sethpyle/pg-backup
    tag: 1.0.1
    imagePullPolicy: IfNotPresent
  calibre:
    image: linuxserver/calibre-web
    tag: 0.6.17
    imagePullPolicy: IfNotPresent
  airsonic:
    image: linuxserver/airsonic
    tag: 10.6.2
    imagePullPolicy: IfNotPresent
  n8n:
    image: n8nio/n8n
    tag: 0.181.2
    imagePullPolicy: IfNotPresent
  nodered:
    image: nodered/node-red
    tag: 2.1.3
    imagePullPolicy: IfNotPresent
  matrix:
    image: matrixdotorg/synapse
    tag: v1.47.0
    imagePullPolicy: IfNotPresent
  delegation:
    image: nginx
    tag: 1.21.4
    imagePullPolicy: IfNotPresent
  searxng:
    image: searxng/searxng
    tag: 2022.06.18-62e88e63
    imagePullPolicy: IfNotPresent
  grafana:
    image: grafana/grafana
    tag: 8.3.2-ubuntu
    imagePullPolicy: IfNotPresent
  matrixdiscord:
    image: sethpyle/matrix-appservice-discord
    tag: 1.0.0
    imagePullPolicy: IfNotPresent
  homeassistant:
    image: homeassistant/home-assistant
    tag: 2021.12
    imagePullPolicy: IfNotPresent
  planka:
    image: meltyshev/planka
    tag: 1.0.0-beta
    imagePullPolicy: IfNotPresent
  teddit:
    image: 1337kavin/teddit
    tag: latest
    imagePullPolicy: IfNotPresent
  redis:
    image: redis
    tag: 6.2.6
    imagePullPolicy: IfNotPresent
  nitter:
    image: quay.io/unixfox/nitter
    tag: build-20220604
    imagePullPolicy: IfNotPresent
  youtube:
    image: quay.io/invidious/invidious
    tag: b5c54b4e410709d93423ca019aaf30579cb53ace-arm64
    imagePullPolicy: IfNotPresent
  nocodb:
    image: nocodb/nocodb
    tag: 0.84.16
    imagePullPolicy: IfNotPresent
  freshrss:
    image: lscr.io/linuxserver/freshrss
    tag: 1.19.2
    imagePullPolicy: IfNotPresent
  piholeexporter:
    image: ekofr/pihole-exporter
    tag: v0.3.0
    imagePullPolicy: IfNotPresent
  flame:
    image: pawelmalak/flame
    tag: multiarch2.3.0
    imagePullPolicy: IfNotPresent
  dashy:
    image: lissy93/dashy
    tag: 2.1.0
    imagePullPolicy: IfNotPresent
  wikijs:
    image: ghcr.io/requarks/wiki
    tag: 2.5
    imagePullPolicy: IfNotPresent


postgres:
  user:
  pass:
  db:
  port: 5432

rss:
  port: 80

n8n:
  port: 5678
  useBasicAuth: true
  user:
  pass:

irc:
  port: 9000

nodered:
  port: 1880

pgBackup:
  s3Bucket:
  discordWebhook:

aws:
  key:
  secret:
  defaultRegion: us-east-1

searxng:
  port: 8080
  secret:
  baseURL:
  replicaCount: 0

planka:
  port: 1337
  connectionString:
  secretKey:

teddit:
  port: 8080
  appID:

redis:
  port: 6379

nitter:
  port: 8080

youtube:
  port: 3000

freshrss:
  port: 80